version: '3.3'

services:

  serviceA:
      image: nginx:latest

      deploy:
          replicas: 1

      #Publish a port in swarm mode 
      ports:
       - target: 8080
         published: 80
         protocol: tcp
         mode: host
