version: '3.3'

services:

  serviceA:
      image: alpine:latest
      command: /bin/sh
      tty: true # -t
      stdin_open: true  # -i

      deploy:
          replicas: 1

  serviceB:
      image: alpine:latest
      command: /bin/sh
      tty: true
      stdin_open: true

      deploy:
          replicas: 1   
