version: '3.3'

services:

  serviceA:
      image: alpine:latest
      command: /bin/sh
      tty: true # -t
      stdin_open: true  # -i
      
      deploy:
          replicas: 1
    
      # Expose host and container port <HOST>:<CONTAINER            
      ports:
         - "8080:8080" 
