version: '3.3'

services:

  serviceA:
      image: nginx:latest

      deploy:
          replicas: 1

      ports:
       - target: 80
         published: 8080
         protocol: tcp
         mode: host
