version: '3.3'

services:

  incrementloop:
      image: image5:2
      deploy:
          replicas: 3

          resources:
            limits:
              cpus: '0.1'
              memory: 100M
          restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3
          update_config:
              parallelism: 1
              delay: 10s
        
  