version: '3.3'

services:

  incrementloop:
      image: encrement:1
      deploy:
          replicas: 3

          restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3
          update_config:
              parallelism: 1
              delay: 10s
        
  